export const SUCCESS_POST_FEEDBACK = 'SUCCESS_POST_FEEDBACK';
export const ERROR_POST_FEEDBACK = 'ERROR_POST_FEEDBACK';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
